# Generated by Django 4.2.2 on 2023-06-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
