version: '3.8'
services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py loaddata initial_data &&
      python manage.py initadmin &&
      python manage.py initusers &&
      python manage.py test &&
      gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    ports:
      - "8000:8000"
    env_file: 
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - api_network

  db:
    container_name: db
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
